var CONVOCATION_HEADERS = Object.freeze([
  'CONVOCATORIA_ID',
  'PARTIDO_ID',
  'COMPETENCIA',
  'TOTAL_OBJETIVO',
  'MIN_PORTEROS_SNAPSHOT',
  'MIN_DEFENSAS_SNAPSHOT',
  'MIN_MEDIOS_SNAPSHOT',
  'MIN_DELANTEROS_SNAPSHOT',
  'MAX_SIN_CONVOCATORIA_SNAPSHOT',
  'ESTADO',
  'GENERADA_EN',
  'GENERADA_POR',
  'APROBADA_EN',
  'APROBADA_POR',
  'ENVIADA_EN',
  'TOTAL_SELECCIONADOS',
  'TOTAL_ALERTAS',
  'OBSERVACIONES'
]);

var CONVOCATION_DETAIL_HEADERS = Object.freeze([
  'DETALLE_ID',
  'CONVOCATORIA_ID',
  'ALUMNO_ID',
  'ELEGIBILITY_STATUS',
  'MOTIVO_NO_ELEGIBLE',
  'FI_ORIGEN_ID',
  'COMPETENCIA_SNAPSHOT',
  'NIVEL_SNAPSHOT',
  'POSICION_PRINCIPAL_SNAPSHOT',
  'POSICION_SECUNDARIA_SNAPSHOT',
  'POSICION_ASIGNADA',
  'PUNTAJE_ASISTENCIA_SNAPSHOT',
  'PRESENCIA_REAL_SNAPSHOT',
  'ROTACION_ANTES',
  'PRIORIDAD_ROTACION',
  'TOTAL_CONVOCATORIAS_PREVIAS',
  'RECOMENDADO_SISTEMA',
  'SELECCIONADO_FINAL',
  'CAMBIO_MANUAL',
  'MOTIVO_CAMBIO',
  'ROTATION_EXCEPTION',
  'ROTACION_DESPUES',
  'ORDEN_PRIORIDAD'
]);

var CONVOCATION_STATES = Object.freeze(['BORRADOR', 'PROPUESTA', 'APROBADA', 'ENVIADA', 'CERRADA']);

if (typeof globalThis !== 'undefined') {
  globalThis.CONVOCATION_DETAIL_HEADERS = CONVOCATION_DETAIL_HEADERS;
  globalThis.CONVOCATION_HEADERS = CONVOCATION_HEADERS;
  globalThis.CONVOCATION_STATES = CONVOCATION_STATES;
}

if (typeof module !== 'undefined') {
  module.exports = {
    CONVOCATION_DETAIL_HEADERS,
    CONVOCATION_HEADERS,
    CONVOCATION_STATES
  };
}
